language: python

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: "nightly"
      env: PRE=--pre
  allow_failures:
    - python : "nightly"

install:
  - pip install --upgrade pip
  - python setup.py install
  - pip install $PRE --upgrade pytest pytest-cov coverage

script:
  - coverage run run_tests.py
  - coverage report -m

after_success:
  - bash <(curl -s https://codecov.io/bash)
